on: [push]

jobs:
  download-manifest-branch:
    runs-on: ubuntu-latest
    name: Downloads the manifest branch
    steps:
    - uses: Javier-varez/google-repo-action@v0.2
      with:
        manifest-url: 'Javier-varez/manifest'
